Is there anything wrong with the following exception handler as written? Will this
code work as intended? 
\begin{lstlisting}[language=java]
try {
	this.epicFail();
} catch (Exception e) {
	...
} catch (ArithmeticException a) {
	...
}
\end{lstlisting}
\begin{answer}
\texttt{Exception} is more broad than \texttt{ArithmeticException}, so the second \texttt{catch} statement is unreachable.  \texttt{catch} statements should filter possible \texttt{Exception} types from specific to broad.
\end{answer}